from . import login
from . import contract
from . import ticket
from . import ticket_list
from . import contract_list
from . import product_list
from . import product_details
from . import ticket_comment
from . import ticket_details
from . import user_create
from . import user_details
from . import otp_validation
from . import user_password_set
from . import accept_ticket
from . import mark_as_complete
from . import category_list
from . import stage_list
from . import product_category_list
from . import in_out_register
from . import refill_request
from . import user_list
from . import parts_add
from . import employee
from . import ticket_create_form
from . import mark_as_done_form
