# -*- coding: utf-8 -*-
{
    'name': "Sales Shop",
    'summary': """Sales Shop""",
    'description': """Sales Shop""",
    "license": "OPL-1",
    "author": "RMPS",
    "version": "16.0.1.0.1",
    "depends": [
        'stock', 'l10n_in', 'mtrmp_product_management', 'multi_branch_base',
        'sale_stock', 'delivery', 'mtrmp_column_parser'
    ],
    "data": [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/data_view.xml',
        'data/email_template.xml',
        # 'report/mass_picklist_report.xml',
        'wizard/sales_shop_operation_view.xml',
        'wizard/excel_header_mapping.xml',
        # 'wizard/excel_sale_mapping_view.xml',
        # 'wizard/import_product_view.xml',
        # 'wizard/export_product_view.xml',
        'wizard/import_return.xml',
        # 'wizard/import_awb_view.xml',
        # 'wizard/import_sale_order_view.xml',
        'wizard/attachment_update_wizard_view.xml',
        'views/sales_shop_views.xml',
        'views/sale_shop_product_view.xml',
        'views/sale_order_inherit_view.xml',
        # 'views/stock_picking_view.xml',
        # 'views/cancelled_action.xml',
        # 'views/import_product_records_view.xml',
        # 'views/account_tax_view.xml',
        # 'views/import_sale_order_records_view.xml',
        # 'views/import_awb_no_view.xml',
        'views/product_public_category_view.xml',
        'views/payment_settlement_view.xml',
        'views/payment_transaction_view.xml',
        'wizard/quality_check_view.xml',
        'wizard/raise_issue_view.xml',
        'wizard/return_product_select.xml',
        'wizard/import_payment_set.xml',
        'views/shop_order_ticket_quality.xml',
        'views/shop_order_ticket.xml',
        'views/product_view.xml',
        'views/shop_fail_log_lines_view.xml',
        'views/shop_log_view.xml'
    ],
    "application": False,
    'installable': True,
}
