# -*- encoding: utf-8 -*-

{
    'name': 'CUE website',
    'description': 'CUE website',
    'category': 'website',
    'sequence': 1000,
    'version': '1.0',
    'depends': ['website', 'product_brand', 'product', 'portal'],
    'images': [
        'static/description/cover.png',
        'static/description/theme_default_screenshot.jpg',
    ],
    'data': [
        'data/tag_data.xml',
        'views/product_brand_inherit.xml',
        'views/thnak_form.xml',
#         'views/change_password.xml',
        'views/product_category_inherits.xml',
        'views/recruitment_academic.xml',
        'views/job_requsest_views.xml',
        'views/product_tag_category.xml',
        'views/product_tag_inherit.xml',
        'views/menu_item.xml',
        'security/ir.model.access.csv',
        'views/blog_template.xml',
        'views/crm_lead_inherit_view.xml',
        'views/website_blog_posts_loop.xml',
        'views/snippets/cue_home_banner.xml',
        'views/snippets/cue_cover.xml',
        'views/snippets/cue_accordion.xml',
        'views/snippets/cue_parallax_cover.xml',
        'views/snippets/cue_r_parallax_cover.xml',
        'views/snippets/cue_parner_parallax_cover.xml',
        'views/snippets/cue_blog_content.xml',
        'views/snippets/cue_partner_location.xml',
        'views/snippets/cue_smart_home_image_text.xml',
        'views/snippets/cue_getting_started.xml',
        'views/snippets/cue_columns.xml',
        'views/snippets/cue_contact_form.xml',
        'views/snippets/cue_text.xml',
        'views/snippets/cue_bridge.xml',
        'views/snippets/cue_out_of_box.xml',
        'views/snippets/cue_text_with_button.xml',
        'views/snippets/cue_quotes.xml',
        'views/snippets/cue_tech_specs.xml',
        'views/snippets/cue_helpme.xml',
        'views/snippets/cue_best_platform.xml',
        'views/snippets/cue_supported_devices.xml',
        'views/snippets/cue_blank_template.xml',
        'views/snippets/cue_bridge_contact.xml',
        'views/snippets/cue_resource_library.xml',
        'views/snippets/cue_blog_box.xml',
        'views/snippets/cue_product_cover.xml',
        'views/snippets/cue_bridge_parallax_long_cover.xml',
        'views/snippets/cue_bridge_plus.xml',
        'views/snippets/cue_bridge_max.xml',
        'views/snippets/cue_cover_smart.xml',
        'views/snippets/cue_recruitment_academic.xml',
        'views/snippets/cue_wizard.xml',
        'views/snippets/cue_partner_wizard.xml',
        'views/website_templates.xml',
        'views/snippets/snippets.xml',
    ],
    'assets': {
        'web.assets_frontend_lazy': [
            'cue_website/static/src/js/file_validation.js',
        ],
        'web.assets_frontend': [
            'cue_website/static/fonts/fonts.scss',
            'cue_website/static/src/scss/main.scss',
            'cue_website/static/src/js/cue_partner_location.js',
            #     'cue_website/static/src/js/support_device_product.js',
            'cue_website/static/src/js/support_device_icon.js',
            'cue_website/static/src/js/cue_best_platform.js',
            'cue_website/static/src/js/cue_wizard_data.js',
            'cue_website/static/src/js/cue_partner_wizard_data.js',
            'cue_website/static/src/js/recources_blog.js',
            # 'cue_website/static/src/js/file_validation.js',
            'cue_website/static/src/js/recruitment_academic.js',
            'cue_website/static/src/xml/*.xml',
        ],

        'web.assets_backend': [
            'cue_website/static/src/xml/thanks_page.xml'
        ]
    },


    'license': 'LGPL-3',
}
