# -*- coding: utf-8 -*-
{
    'name': "Reddot Report Automate",
    'summary': """Reddot Report Automate""",
    'author': "Reddot Report Automate",
    'category': 'Uncategorized',
    'version': '0.8',
    'author': "Reddot Distribution",
    "website": "https://reddotdistribution.com",
    'depends': [
        'base',
        'mail',
        'hr_contract',
        'hr_payroll',
        'hr_attendance',
        'hr_holidays',
        'hr_expense',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/contract_reminder_crone.xml',
        'data/anniversary_reminder_crone.xml',
        'data/contract_send_mail_template.xml',
        'data/birthday_anniversay_template.xml',
        'data/report_automation_config_data.xml',
        'wizard/attendance_summary_report.xml',
        'reports/payroll_analysis_report_view.xml',
        'views/email_templats_view.xml',
        'views/hr_contract_history_view.xml',
        'views/report_automation_config_view.xml',
        'views/hr_expense_inherit_view.xml',
        'views/schedule_action_view.xml',
    ],
}
