# -*- coding: utf-8 -*-
# Part of Kiran Infosoft. See LICENSE file for full copyright and licensing details.
{
    'name': "Contract Extension",
    'summary': """""",
    'description': "",
    "version": "14.0",
    "category": "Contract",
    'author': "Kiran Infosoft",
    "website": "https://www.kiraninfosoft.com",
    'license': 'Other proprietary',
    "depends": [
        'account',
        'base',
        'contract',
        'product',
        'stock',
        'purchase',
        'ki_helpdesk_extention',
        'helpdesk_mgmt',
        'l10n_in',
    ],
    "data": [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/data_view.xml',
        'data/sequence_data.xml',
        'wizard/contract_terminate_reasion_wizard.xml',
        'wizard/product_serial_number_wizard.xml',
        'wizard/contact_create_wizard_view.xml',
        'wizard/create_purchase_order_wizard_view.xml',
        'wizard/select_product_template_wizard_view.xml',
        'report/report.xml',
        'report/template_report.xml',
        'report/contract_report.xml',
        'report/product_number_report_template.xml',
        'report/cartridge_report_template.xml',
        'views/contract_line_view.xml',
        'views/contract_view.xml',
        'views/customer_view.xml',
        'views/product_view.xml',
        'views/product_part_line_view.xml',
        # 'views/cartridge_view.xml',
        'views/menu_item.xml',
        'views/product_category_view.xml',
        'views/product_in_out_register_view.xml',
        'views/purchase_view.xml',
        'views/refill_request_view.xml',
    ],
    'installable': True,
}
