{
    'name': 'Inherit Model',
    'version': '12.0.1.0.2',
    'author': 'RDP',
    'category': 'Customizations',
    'depends': ['base', 'mail',
                'stock',
                'product',
                'stock_account',
                'purchase_stock',
                'account',
                'sale_stock', 'mrp',
                'sale',
                'rdp_it_custom_module_ev12_custom',
                'rdp_source_document',
                'ki_accounting_reports',
                'hr_expense',
                'account',
                'product',
                ],
    'data': [
        'views/purchase_order.xml',
        'views/account_move.xml',
        'views/sale_order.xml',
        'views/stock_picking.xml',
        'views/account_payment.xml',
        'views/account_move_line.xml',
        'views/mrp_production.xml',
        'views/stock_scrap.xml',
        'views/stock_move.xml',
        'views/stock_inventory.xml',
        'views/account_invoice.xml',
        'views/account_invoice_line.xml',
        'views/mrp_unbuild.xml',
        'views/hr_expense.xml',
        'views/load_js_file.xml',
        'views/res_partner.xml'

    ],

    'installable': True,
    'application': False,
    'auto_install': False,
}
